In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import dask.dataframe as dd
import itertools
import matplotlib.pyplot as plt

In [4]:
from Ipython.display import Image

ModuleNotFoundError: No module named 'Ipython'

In [5]:
a,b,c = [1,2,3]

In [6]:
a,b,c

(1, 2, 3)

In [7]:
l=[1,2,3,4,5]

In [8]:
l[-2]

4

In [9]:
l[-3:-1]

[3, 4]

In [10]:
a=['cat','dog','rat']

In [11]:
",".join(a)

'cat,dog,rat'

In [12]:
['a','b','c']

['a', 'b', 'c']

In [13]:
'a b c'.split(" ")

['a', 'b', 'c']

In [14]:
l[::-1]

[5, 4, 3, 2, 1]

In [15]:
"cat" * 4

'catcatcatcat'

In [16]:
s='abcbde'

In [17]:
s[::-1]

'edbcba'

In [18]:
for i, e in enumerate(l):
    print(i,e)

0 1
1 2
2 3
3 4
4 5


In [19]:
dictionary = {'spain' : 'madrid', 'france':'paris'}
for key,value in dictionary.items():
    print(key," : ", value)
print('')

spain  :  madrid
france  :  paris



In [20]:
a=[1,2,3]
b=['a','b','c']
c = [6,7,8]

In [21]:
z=zip(a,b,c)

In [22]:
for e in z:
    print(e)

(1, 'a', 6)
(2, 'b', 7)
(3, 'c', 8)


In [23]:
dictionary

{'spain': 'madrid', 'france': 'paris'}

In [25]:
dict(zip(dictionary.values() , dictionary.keys()))

{'madrid': 'spain', 'paris': 'france'}

In [26]:
a=[[1,2],[3,4],[5,6,7]]

In [27]:
list(itertools.chain.from_iterable(a))

[1, 2, 3, 4, 5, 6, 7]

In [28]:
sum(a, [])

[1, 2, 3, 4, 5, 6, 7]

In [29]:
m = { i: i*4 for i in range(10)}
m

{0: 0, 1: 4, 2: 8, 3: 12, 4: 16, 5: 20, 6: 24, 7: 28, 8: 32, 9: 36}

In [30]:
dictionary

{'spain': 'madrid', 'france': 'paris'}

In [31]:
{v:k for k, v in dictionary.items()}

{'madrid': 'spain', 'paris': 'france'}

In [34]:
a=[1,2,3]
it = iter(a)
next(it)


1

In [37]:
a = "abcdef"
it = iter(a)
print(*it)

a b c d e f


In [38]:
a={"a":1,"B": 3,"c":3}
it = iter(a)
next(it)

'a'

In [40]:
from Ipython.display import Image

ModuleNotFoundError: No module named 'Ipython'

In [41]:
1-d

NameError: name 'd' is not defined

In [43]:
l=[1,2,3]
a=np.array(l)

In [44]:
a.shape

(3,)

In [46]:
a+2

array([3, 4, 5])

In [47]:
l+2

TypeError: can only concatenate list (not "int") to list

In [48]:
a2 = np.array([[1,2],[3,4]])

In [49]:
a2.shape

(2, 2)

In [50]:
np.array([[1,2],[3,4]] ,dtype='float')

array([[1., 2.],
       [3., 4.]])

In [51]:
a2.astype('float')

array([[1., 2.],
       [3., 4.]])

In [52]:
np.array([[1,2,3],[3,4]])

array([list([1, 2, 3]), list([3, 4])], dtype=object)

In [54]:
k=np.array([[1,2,3],[3,4]])
print(k)


[list([1, 2, 3]) list([3, 4])]


In [56]:
arr1d_obj = np.array([1,'a'], dtype = 'object')

In [57]:
arr1d_obj.shape

(2,)

In [59]:
arr1d_obj.size

2

a2.tolist

In [60]:
a2.tolist()

[[1, 2], [3, 4]]

In [61]:
arr1d_obj.tolist()

[1, 'a']

In [62]:
list2 = [[1,2,3,4],[3,4,5,6],[5,6,7,8]]
arr2 = np.array(list2, dtype='float')
arr2

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.],
       [5., 6., 7., 8.]])

In [63]:
arr2[:2, :1] 

array([[1.],
       [3.]])

In [64]:
mask = arr2>4

In [65]:
arr2[mask]

array([5., 6., 5., 6., 7., 8.])

In [66]:
list2 = [[1,2,3,4],[3,4,5,6],[5,6,7,8]]
arr2 = np.array(list2,dtype='float')
arr2

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.],
       [5., 6., 7., 8.]])

In [71]:
arr2[::-1 ,::-1]

array([[8., 7., 6., 5.],
       [6., 5., 4., 3.],
       [4., 3., 2., 1.]])

In [77]:
arr2[1,1] = np.nan

In [73]:
arr2[1,2] = np.inf

In [74]:
arr2

array([[ 1.,  2.,  3.,  4.],
       [ 3., nan, inf,  6.],
       [ 5.,  6.,  7.,  8.]])

In [78]:
np.isnan(arr2)

array([[False, False, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [79]:
np.isinf(arr2)

array([[False, False, False, False],
       [False, False,  True, False],
       [False, False, False, False]])

In [80]:
np.isnan(arr2) | np.isinf(arr2)

array([[False, False, False, False],
       [False,  True,  True, False],
       [False, False, False, False]])

In [82]:
arr2[np.isnan(arr2) | np.isinf(arr2)]=-1

In [83]:
arr2

array([[ 1.,  2.,  3.,  4.],
       [ 3., -1., -1.,  6.],
       [ 5.,  6.,  7.,  8.]])

In [88]:
np.cumsum(arr2,axis=0)

array([[ 1.,  2.,  3.,  4.],
       [ 4.,  1.,  2., 10.],
       [ 9.,  7.,  9., 18.]])

In [89]:
arr2.shape







(3, 4)

In [90]:
arr2.reshape(4,3)

array([[ 1.,  2.,  3.],
       [ 4.,  3., -1.],
       [-1.,  6.,  5.],
       [ 6.,  7.,  8.]])

In [91]:
arr2.T

array([[ 1.,  3.,  5.],
       [ 2., -1.,  6.],
       [ 3., -1.,  7.],
       [ 4.,  6.,  8.]])

In [92]:
arr= np.array([1,2,3])

In [93]:
arr

array([1, 2, 3])

In [94]:
arr.shape

(3,)

In [95]:
arr[None].shape

(1, 3)

In [96]:
a3 = arr2.flatten()

In [97]:
a3[1] = 100

In [98]:
a3

array([  1., 100.,   3.,   4.,   3.,  -1.,  -1.,   6.,   5.,   6.,   7.,
         8.])

In [99]:
a3=arr2.ravel()

In [100]:
a3[1]=100

In [101]:
a3

array([  1., 100.,   3.,   4.,   3.,  -1.,  -1.,   6.,   5.,   6.,   7.,
         8.])

In [102]:
arr2.reshape(6,-1).shape

(6, 2)

In [103]:
arr2.resize((4,3))

In [104]:
arr2

array([[  1., 100.,   3.],
       [  4.,   3.,  -1.],
       [ -1.,   6.,   5.],
       [  6.,   7.,   8.]])

In [105]:
arr2

array([[  1., 100.,   3.],
       [  4.,   3.,  -1.],
       [ -1.,   6.,   5.],
       [  6.,   7.,   8.]])

In [106]:
arr1=arr2.T

In [107]:
arr1

array([[  1.,   4.,  -1.,   6.],
       [100.,   3.,   6.,   7.],
       [  3.,  -1.,   5.,   8.]])

In [108]:
np.dot(arr1,arr2)

array([[   54.,   148.,    42.],
       [  148., 10094.,   383.],
       [   42.,   383.,    99.]])

In [112]:
np.multiply(arr2, arr2)

array([[1.0e+00, 1.0e+04, 9.0e+00],
       [1.6e+01, 9.0e+00, 1.0e+00],
       [1.0e+00, 3.6e+01, 2.5e+01],
       [3.6e+01, 4.9e+01, 6.4e+01]])

In [111]:
arr2

array([[  1., 100.,   3.],
       [  4.,   3.,  -1.],
       [ -1.,   6.,   5.],
       [  6.,   7.,   8.]])

In [113]:
np.exp(arr1)

array([[2.71828183e+00, 5.45981500e+01, 3.67879441e-01, 4.03428793e+02],
       [2.68811714e+43, 2.00855369e+01, 4.03428793e+02, 1.09663316e+03],
       [2.00855369e+01, 3.67879441e-01, 1.48413159e+02, 2.98095799e+03]])

In [114]:
np.array([1,2,3])

array([1, 2, 3])

In [115]:
a.shape

(3,)

In [116]:
a+1

array([2, 3, 4])

In [117]:
arr2

array([[  1., 100.,   3.],
       [  4.,   3.,  -1.],
       [ -1.,   6.,   5.],
       [  6.,   7.,   8.]])

In [118]:
arr2.shape

(4, 3)

In [119]:
a.shape

(3,)

In [120]:
arr2+a

array([[  2., 102.,   6.],
       [  5.,   5.,   2.],
       [  0.,   8.,   8.],
       [  7.,   9.,  11.]])

In [121]:
np.broadcast_to(a,arr2.shape)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [122]:
np.arrange(4)

AttributeError: module 'numpy' has no attribute 'arrange'

In [123]:
np.arange(4)

array([0, 1, 2, 3])

In [124]:
np.arange(3,8)

array([3, 4, 5, 6, 7])

In [125]:
np.linspace(0, 100, num=4)

array([  0.        ,  33.33333333,  66.66666667, 100.        ])

In [126]:
np.linspace(0,100,num=4,dtype='int')

array([  0,  33,  66, 100])

In [127]:
np.logspace(0,3,num=3)

array([   1.       ,   31.6227766, 1000.       ])

In [128]:
np.zeros([1,3])

array([[0., 0., 0.]])

In [130]:
a = [1,2,3]
np.tile(a,2)


array([1, 2, 3, 1, 2, 3])

In [131]:
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [132]:
np.random.rand(2,2)

array([[0.88390059, 0.62843409],
       [0.17414163, 0.97372441]])

In [140]:
np.random.randint(0, 10, [2,2])

array([[1, 3],
       [7, 7]])

In [141]:
np.random.random([2,2])

array([[0.02426289, 0.64324883],
       [0.14820085, 0.67235096]])

In [143]:
np.random.choice(['a','e','i','o','u'],size=10)

array(['e', 'e', 'a', 'a', 'u', 'u', 'i', 'a', 'u', 'a'], dtype='<U1')

In [144]:
rn = np.random.RandomState(100)

In [145]:
rn.rand(2,2), rn.rand(3,3)

(array([[0.54340494, 0.27836939],
        [0.42451759, 0.84477613]]),
 array([[0.00471886, 0.12156912, 0.67074908],
        [0.82585276, 0.13670659, 0.57509333],
        [0.89132195, 0.20920212, 0.18532822]]))

In [146]:
np.random.seed(100)
a = np.random.choice(['a','e','i','o','u'],size=100)
a

array(['a', 'a', 'o', 'a', 'i', 'u', 'i', 'i', 'i', 'i', 'e', 'a', 'a',
       'u', 'o', 'u', 'i', 'a', 'o', 'e', 'i', 'o', 'u', 'u', 'e', 'o',
       'u', 'u', 'o', 'o', 'o', 'e', 'e', 'o', 'a', 'i', 'e', 'e', 'o',
       'i', 'o', 'a', 'e', 'a', 'u', 'i', 'a', 'a', 'i', 'i', 'e', 'a',
       'i', 'e', 'u', 'i', 'a', 'o', 'o', 'o', 'a', 'e', 'u', 'i', 'o',
       'o', 'u', 'i', 'u', 'o', 'e', 'a', 'u', 'o', 'u', 'i', 'i', 'u',
       'i', 'u', 'e', 'i', 'i', 'a', 'i', 'i', 'o', 'u', 'i', 'u', 'o',
       'e', 'a', 'a', 'e', 'i', 'u', 'i', 'o', 'o'], dtype='<U1')

In [147]:
np.random.seed(100)
a = np.random.choice(['a','e','i','o','u'],size=10)

In [148]:
a

array(['a', 'a', 'o', 'a', 'i', 'u', 'i', 'i', 'i', 'i'], dtype='<U1')

In [149]:
np.unique(a,return_counts=True)

(array(['a', 'i', 'o', 'u'], dtype='<U1'), array([3, 5, 1, 1], dtype=int64))

In [150]:
arr_rand = np.array([8,8,3,7,7,0,4,2,5,2])

In [152]:
pos = np.where(arr_rand > 5)

In [153]:
pos

(array([0, 1, 3, 4], dtype=int64),)

In [1]:
import pandas as pd

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("weather_data.csv")

FileNotFoundError: [Errno 2] File b'weather_data.csv' does not exist: b'weather_data.csv'

In [8]:
weather_data = {'day': ['1/1/2017','1/2/2017','1/3/2017','1/4/2017','1/5/2017','1/6/2017'],
                 'temperature': [32,35,28,24,32,31],
                 'windspeed':[6,7,2,7,4,2],
                'event': ['Rain','sunny','Snow','Snow','Rain','sunny']
               }
df = pd.DataFrame(weather_data)
df

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  sunny

In [10]:
rows,columns = df.shape

In [11]:
rows

6

In [15]:
df.tail(2)

day  temperature  windspeed  event
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  sunny

In [18]:
df

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  sunny

In [19]:
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [22]:
df['day']

0    1/1/2017
1    1/2/2017
2    1/3/2017
3    1/4/2017
4    1/5/2017
5    1/6/2017
Name: day, dtype: object

In [23]:
type(df['event'])

pandas.core.series.Series

In [24]:
df[['event','day']]

event       day
0   Rain  1/1/2017
1  sunny  1/2/2017
2   Snow  1/3/2017
3   Snow  1/4/2017
4   Rain  1/5/2017
5  sunny  1/6/2017

In [25]:
df

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  sunny

In [30]:
df.describe()

temperature  windspeed
count     6.000000   6.000000
mean     30.333333   4.666667
std       3.829708   2.338090
min      24.000000   2.000000
25%      28.750000   2.500000
50%      31.500000   5.000000
75%      32.000000   6.750000
max      35.000000   7.000000

In [33]:
df[df.temperature==df['temperature'].max()]

day  temperature  windspeed  event
1  1/2/2017           35          7  sunny

In [34]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [43]:
df.set_index('day', inplace=True)

KeyError: 'day'

In [45]:
df.set_index('day')

KeyError: 'day'

In [50]:
df.reset_index('day',inplace=True)

KeyError: 'Level day must be same as name (None)'

In [51]:
df.reset_index('day',inplace=True)

KeyError: 'Level day must be same as name (None)'

In [52]:
df.reset_index(inplace=True)
df

index       day  temperature  windspeed  event
0      0  1/1/2017           32          6   Rain
1      1  1/2/2017           35          7  sunny
2      2  1/3/2017           28          2   Snow
3      3  1/4/2017           24          7   Snow
4      4  1/5/2017           32          4   Rain
5      5  1/6/2017           31          2  sunny

In [53]:
df.set_index('event',inplace=True)

In [54]:
df

index       day  temperature  windspeed
event                                         
Rain       0  1/1/2017           32          6
sunny      1  1/2/2017           35          7
Snow       2  1/3/2017           28          2
Snow       3  1/4/2017           24          7
Rain       4  1/5/2017           32          4
sunny      5  1/6/2017           31          2

In [55]:
df.loc['Snow']

index       day  temperature  windspeed
event                                         
Snow       2  1/3/2017           28          2
Snow       3  1/4/2017           24          7

In [56]:
a=2

In [58]:
weather_data = {'day': ['1/1/2017','1/2/2017','1/3/2017','1/4/2017','1/5/2017','1/6/2017'],
                 'temperature': [32,35,28,24,32,31],
                 'windspeed':[6,7,2,7,4,2],
                'event': ['Rain','sunny','Snow','Snow','Rain','sunny']
               }
df = pd.DataFrame(weather_data)
df

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  sunny